### ISSUE TITLE
ops: get keycloak and server to communicate within docker compose

### ISSUE THREAD

**Issue by cdxker** [devflowinc/trieve#1474]
### Community channels

Matrix is preferred. Reach out on discord or Matrix for further assistance. 

- [discord](https://discord.gg/CuJVfgZf54)
- [matrix](https://matrix.to/#/#trieve-general:matrix.zerodao.gg)

**Comment by cdxker** [comment]
The issue seems to be with the docker network inside of itself.

**Comment by jooni22** [comment]
This is a common problem in communicating with the API on docker-compos, it can be solved by implementing CORS support in the application code, there are several solutions in several popular languages, you can follow them and add support in the code. You can read more under this post:
https://maximillianxavier.medium.com/solving-cors-problem-on-local-development-with-docker-4d4a25cd8cfe

(NOTE! this solution works only on Linux systems)
Another solution is to move the API Server outside the internal docker network and use the attribute:
    network_mode: "host"
instead of:
    networks:
      - app-network
In order for the app to work correctly with the current logic, the "ingestion-worker" and "file-worker" services must also be moved to the "host" network.
