### ISSUE TITLE
feature: worker that does batch update for groups to pass down it's metadata and tags

### ISSUE THREAD

**Issue by skeptrunedev** [devflowinc/trieve#1628]
### Description

When a group is updated, pass down those updates to its chunks. 

### Target(s)

`server`

### Requirement to close

PR which adds a worker to handle batch updating chunks when a group's data updates. 

### Community channels

Matrix is preferred. Reach out on discord or Matrix for further assistance. 

- [discord](https://discord.gg/CuJVfgZf54)
- [matrix](https://matrix.to/#/#trieve-general:matrix.zerodao.gg)

**Comment by densumesh** [comment]
Instead of making changes in postgres for the tags, add a new field in the QdrantPayload objext for group_metadata and group_tag_set and have those be updated in the group_update worker. Make sure you create a payload index on `group_ids` and `group_metadata` in qdrant in the qdrant_operator.rs when you initalize qdrant.
