### ISSUE TITLE
"semantic_boost" option cause Deserialization Error.

### ISSUE THREAD

**Issue by yujonglee** [devflowinc/trieve#2620]
### Description

```bash
curl -X POST "https://api.trieve.ai/api/chunk" \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer <api_key>" \
  -H "TR-Dataset: <dataset_id>" \
  -d '{
    "chunk_html": "content",
    "semantic_boost": {
      "boost_factor": 5,
      "phrase": "phrase"
    }
  }'
```

Got:

```json
{"message":"Json Deserialization Error: *Type* : Data error in JSON | *Message* : Json deserialize error: data did not match any variant of untagged enum CreateChunkReqPayloadEnum | Ensure that the data in the JSON payload is valid and consistent with the expected schema."}%
```

### Target(s)

server

### Requirement to close

Above curl should succeed, or docs should updated.

### Community channels

Matrix is preferred. Reach out on discord or Matrix for further assistance. 

- [discord](https://discord.gg/CuJVfgZf54)
- [matrix](https://matrix.to/#/#trieve-general:trieve.ai)

**Comment by yujonglee** [comment]
@skeptrunedev  thanks. FYI, `fulltext_boost` works as expected.

**Comment by skeptrunedev** [comment]
Looked into this more and it we actually used `distance_factor` instead of `boost_factor` for `semantic_boost` which is what caused the deserialization error. 

Connected PR to this issue allows the API consumer to use `boost_factor` in addition to `distance_factor` now. Might as well allow both so it's less of a footgun.
