### ISSUE TITLE
feature: upload from pdf2md incrementallyu rather than just at the end

### ISSUE THREAD

**Issue by densumesh** [devflowinc/trieve#2930]
### Description

<replace w/ a helpful description of your issue, including steps to replicate when/if relevant>

### Target(s)

<replace w/ name of the service(s) which are associated with this issue>

### Community channels

Matrix is preferred. Reach out on discord or Matrix for further assistance. 

- [discord](https://discord.gg/CuJVfgZf54)
- [matrix](https://matrix.to/#/#trieve-general:trieve.ai)

**Comment by vtempest** [comment]
https://airesearch.js.org/functions/convertPDFToHTML.html
I've checked out the pdf2md but think how will that scale to 10k PDFs
That's why you need a hybrid use my 0$ version which also does reference extraction 
Then ocr images tables only if needed by the prompt about that chunk. But not summarize or topicify types of prompts. Otherwise this is a very expensive overkill to use gpt token many PDFs

Nick Khami (@skeptrune) is probably telling you all to ingore me which is violating open source code of conduct for welcoming environment when he passive aggressively looks for bs excuse to block me ignoring my years of research ideas many of which he later adopted like switching to HF vector and pdf2md. This is not the way to handle it hoping I go away instead talk it out apologize and include qualified developers. If you're hoping I will shut up then this will only get far worse over next 20y with your vcs all seeing news articles about your toxic free speech. That's the same reason you discriminated against me from the start and even undermined me, now you'll get equal treatment.
ttps://github.com/devflowinc/trieve/blob/main/CODE_OF_CONDUCT.md
